baseURL = 'http://hariprakash.in/'
languageCode = 'en-us'
title = 'Hari Prakash'
theme = "hyde"

[params]
  description = "Cloud & DevOps Engineer"
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/hariprakash-j"}
  ]
