baseURL = "https://hariprakash.dev"
title = "Hari's blog"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
uglyURLs = true

[params]
  description = "A personal tech blog"
  copyright = "Copyright © 2023 Hari Prakash J"
  dark = "off"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about me"
    title = "about me"
    url = "/about-me.html"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
